### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by mallimuondu** [muondu/Nesh-hotel#3]
when I choose  Cinema in has an error it says:
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    c.execute('SELECT * FROM movilunch_billes')
sqlite3.OperationalError: no such table: movilunch_billes

**Comment by mallimuondu** [comment]
sports has an error it says:

Traceback (most recent call last):
  File "main.py", line 130, in <module>
    c.execute('SELECT * FROM sports')
sqlite3.OperationalError: no such table: sports
